### ISSUE TITLE
Accessing h5 files give out file format errors

### ISSUE THREAD

**Issue by Karthik777** [daavoo/3D_Deep_Learning#1]
Hi,
When I try to access the h5 files via a viewer it throws an invalid format error. I use hdfviewer in ubuntu 14.04. And the gz file shows a file format error as well. But the files downloaded through kaggle work correctly but they do not have labels in them.

**Comment by daavoo** [comment]
Hi!. sorry for late response.

I just cloned this repo an run the notebooks and everithing works fine for me.

The kaggle thing is strange too. I just downloaded the dataset again and open the file using h5py and there are labels and point clouds.

I really don't know why you are getting this errors using hdfviewer.

**Comment by daavoo** [comment]
The 3D MNIST dataset now don't make use of h5 files but instead builds a directory ready to be used by dataset_to_feature_vectors.py.

**Comment by Karthik777** [comment]
Thanks. This works fine now
